spring:
  jpa:
    database: mysql
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  datasource:
    url: jdbc:mysql://localhost:3306/book
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    org.hibernate.SQL: debug